
version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skinova
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - skinova-network

  

volumes:
  postgres_data:

networks:
  skinova-network:
    driver: bridge